### ISSUE TITLE
Error initializing

### ISSUE THREAD

**Issue by Brycey92** [SettingDust/DustSponge#2]
When I install Nucleus 1.9.3, DustCore 1.4 and DustMultiRespawn 1.4, DustMultiRespawn fails to initialize, specifically when it tries to remove the spawn module from Nucleus:
https://gist.github.com/Brycey92/ecf0b57030534c29dbae991497a4e88f

**Comment by Brycey92** [comment]
This was an issue in Nucleus, and has been fixed in 1.10.0.

**Comment by SettingDust** [comment]
> This was an issue in Nucleus, and has been fixed in 1.10.0.

Yes, I reported this and he resloved.
