### ISSUE TITLE
Error on game start

### ISSUE THREAD

**Issue by Brycey92** [SettingDust/DustSponge#3]
When I install DustCore 1.4 and DustMultiRespawn 1.4, DustMultiRespawn encounters an error on game start. It seems to happen when SpawnsCommand's constructor tries to load a node from the locale, which may be null.
https://gist.github.com/Brycey92/3689fedc5fc0bb82e2d4dc654b4d81fd

**Comment by SettingDust** [comment]
Thanks. [536e637](https://github.com/SettingDust/DustSponge/commit/536e63759af8c3b782dbf16bf82dff3f07464d1c)

https://ore.spongepowered.org/SettingDust/DustMultiRespawn/versions/1.41

**Comment by Brycey92** [comment]
Oops! It looks like there was something else causing this issue. It still happens on DustMultiRespawn 1.41: https://gist.github.com/Brycey92/c0aeb4a23f05f9dfab98392433a2522c

**Comment by Brycey92** [comment]
I found out that in Sponge's plugin config directory, the bugged lang files aren't overwritten.

**Comment by SettingDust** [comment]
@Brycey92 yep, plz read my update log on ore
